### PR TITLE
1.19.3

### PR DESCRIPTION
**Pull request by yu-re-ka**

### CODE REVIEW

**Comment by venaminecraft** [comment]
Hello @yu-re-ka, thank you for updating the mod.
I am not able to build it myself, could you make it please as (temporary) download available?
Thanks already 😊

**Comment by TheIllusiveC4** [comment]
I've released the official 1.19.3 version. Thank you for the PR, unfortunately I was unable to merge due to other changes I needed to perform on the codebase however it was still helpful to use as a reference.

**Comment by venaminecraft** [comment]
Thanks!!

**Comment by venaminecraft** [comment]
I see just the 1.19.2 version as new upload on Curse - does it need longer sometimes to publish newer builds @TheIllusiveC4? 😅

**Comment by TheIllusiveC4** [comment]
It just depends on how long it takes Curse to approve it, it's not up to me once I've uploaded it. But do note that I've consolidated all versions onto [this](https://www.curseforge.com/minecraft/mc-mods/charm-of-undying) page if you've been looking at the other page instead.

**Comment by venaminecraft** [comment]
Ah, the 1.19.3 builds are available now - great 🥳
I would love to see the other Trinket related mods updated too, but no rush please.

**Pull request closed without merging**
